### ISSUE TITLE
Add Complex routing example involving conditional Split and Loop

### ISSUE THREAD

**Issue by kovax** [cristal-ise/testing#2]
set root CA property: counter=0
    EA()
    Loop(counter < 100) {
        OrSplit (counter % 2) {
           (EA())
           (
               AndSplit {
                      (EA)
                      (EA)
               }
           )
        }
    }

**Comment by ogattaz** [comment]
A "complex" balanced WF to test the routings (OR and LOOP) using a property of the RootCA (eg. counter)
![img_20150818_115239](https://cloud.githubusercontent.com/assets/5037130/9328258/7ff4f2c4-45a7-11e5-9ff6-0f4549823a8e.png)

**Comment by kovax** [comment]
Done: org.cristalise.kernel.test.lifecycle.instance.BalancedRoutingScriptTest
